### ISSUE TITLE
Upgrade to 0.19

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/elm-examples#9]
- [x] Elm Fractal Architecture
- [x] HTTP GET with Elm
- [x] Key combinations with Subscription
- [x] Generic update function
- [x] Module composition in Elm
- [x] Module composition in Elm with tagger function
- [x] JavaScript interop with Elm
- [x] Random value with user-specified seed
- [x] Select2 integration into Elm application
- [x] Elm SPA using Create Elm App

**Comment by FranklinChen** [comment]
I'm actually almost done with an upgrade to 0.19 of all the examples on my elm-0.19 branch, and will submit a pull request when I'm done. I'm finishing "Elm Fractal Architecture" and "Select2 integration".

**Comment by halfzebra** [comment]
That's awesome!

Your PR is very welcome 🙂
